# Generated by Django 5.1.6 on 2025-02-20 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('MERN', 'MERN'), ('Django', 'Django'), ('WebTech', 'WebTech'), ('SQL', 'SQL'), ('MongoDB', 'MongoDB'), ('Bootstrap', 'Bootstrap')], default='Python', max_length=50)),
                ('communicating', models.CharField(default='1', max_length=50)),
                ('technical', models.CharField(default='1', max_length=50)),
                ('programming', models.CharField(default='1', max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('conducted_on', models.DateField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
