# Generated by Django 5.1.6 on 2025-02-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='communicating',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='programming',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='technical',
            field=models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=50),
        ),
    ]
