# Generated by Django 5.1.6 on 2025-02-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_pno_studentprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='add',
            field=models.CharField(max_length=50),
        ),
    ]
