# Generated by Django 5.1.6 on 2025-02-27 06:42

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(upload_to=student.models.StudentProfile.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
